Improve checking and loading of default config files

diff --git a/bsdeb b/bsdeb
--- a/bsdeb
+++ b/bsdeb
@@ -6,10 +6,11 @@ set -e
 PROGRAM_NAME="Debian Bootstrapper"
 PROGRAM_VERSION="1.0.0-SNAPSHOT"
 DEBIAN_VERSION=12.2
-CONFIG_FILENAME="server.conf"
 REPO_SOURCE_URL="https://github.com/genebarker/debian/raw/master"
 SCRIPT_FILENAME="$(basename ${BASH_SOURCE})"
 BASE_DIR="$(dirname ${BASH_SOURCE})"
+CONFIG_FILENAME="server.conf"
+CONFIG_FILEPATH="${BASE_DIR}/${CONFIG_FILENAME}"
 BOOTSTRAP=OFF
 AUTO_YES=OFF
 
@@ -74,7 +75,7 @@ parse_script_options()
                 BOOTSTRAP=ON
                 ;;
             f)
-                override_config_filepath "$OPTARG"
+                override_config_file "$OPTARG"
                 ;;
             y)
                 AUTO_YES=ON
@@ -98,15 +99,13 @@ parse_script_options()
     shift $((OPTIND-1))
 }
 
-override_config_filepath()
+override_config_file()
 {
-    local filepath=$1
-    if [ -f $1 ]
+    CONFIG_FILEPATH=$1
+    CONFIG_FILENAME=$(basename "$CONFIG_FILEPATH")
+    if [ ! -f $1 ]
     then
-        CONFIG_FILEPATH=$filepath
-    else
-        show_error "Config file ($filepath) not found."
-        exit 1
+        echo "Config file (${CONFIG_FILENAME}) not found, will try to download from repo."
     fi
 }
 
@@ -135,9 +134,9 @@ verify_bootstrap_selected()
 
 verify_and_load_config_file()
 {
-    if [ -z "$CONFIG_FILEPATH" ]
+    if [ -f "$CONFIG_FILEPATH" ]
     then
-        get_default_config
+        get_config_file_from_repo_and_exit
     fi
     echo ".. config file set ($CONFIG_FILEPATH)"
     echo ".. displaying config"
@@ -149,34 +148,17 @@ verify_and_load_config_file()
     echo ".. config file loaded"
 }
 
-get_default_config()
+get_config_file_from_repo_and_exit()
 {
-    CONFIG_FILEPATH="${BASE_DIR}/${CONFIG_FILENAME}"
-    if ! has_default_config_file
-    then
-        download_default_config_file
-        echo -n "Update config file ${CONFIG_FILEPATH} with your settings, "
-        echo "then rerun this script."
-        exit 1
-    fi
+    download_config_file
+    echo -n "Update config file ${CONFIG_FILEPATH} with your settings, "
+    echo "then rerun this script."
+    exit 1
 }
 
-has_default_config_file()
+download_config_file()
 {
-    echo ".. verifying default config file present"
-    if [ -f ${CONFIG_FILEPATH} ]
-    then
-        echo ".. found default config file (${CONFIG_FILENAME})"
-        return 0
-    else
-        echo ".. no default config file found (${CONFIG_FILENAME})"
-        return 1
-    fi
-}
-
-download_default_config_file()
-{
-    echo ".. downloading default config file from repo"
+    echo ".. downloading config file from repo"
     wget ${REPO_SOURCE_URL}/${CONFIG_FILENAME}
     echo ".. config file download successful"
 }
